### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by noraj** [lsegal/yardoc.org#10]
[yardoc.org/templates/home.erb](https://github.com/lsegal/yardoc.org/blob/master/templates/home.erb)

```html
 A full list can be found <a href="https://github.com/lsegal/yard/wiki/Who's-Using-YARD%3F">here</a>.</p> 
```

The link is dead because wiki is not more public so this is redirecting to https://github.com/lsegal/yard.

**Comment by lsegal** [comment]
Fixed by re-enabling the wiki. Thanks!
