### ISSUE TITLE
Guides doesn't work

### ISSUE THREAD

**Issue by johanlunds** [lsegal/yardoc.org#7]
Link: http://yardoc.org/docs/yard/file/docs/GettingStarted.md

Screenshot:

![yard_-_a_ruby_documentation_tool_and_new_issue_ _lsegal_yardoc_org](https://cloud.githubusercontent.com/assets/22144/8872275/cff42d90-31fb-11e5-9079-ec7b63121b72.png)

Lots of links on http://yardoc.org/guides/index.html just lead to the above page.

**Comment by lsegal** [comment]
Should be resolved now thanks for reporting!

**Comment by johanlunds** [comment]
Thanks!
